forge 'http://forge.puppetlabs.com'

mod 'puppetlabs/java', '>=1.0.0'
mod 'puppetlabs/apache', '>=0.9.0'
mod 'puppetlabs/postgresql', '>=3.0.0'
mod 'puppetlabs/firewall'
mod 'camptocamp/tomcat', '>=0.6.0'
mod 'maestrodev/maven', '>=1.0.0'
mod 'stahnma/epel', '>=0.0.2'
mod 'maestrodev/avahi', '>=1.0.0'
mod 'carlossg/acme', :path => 'mymodules/acme'
